README.md
app/controllers/ApplicationController.java
app/controllers/SunriseController.java
app/io/sphere/sdk/play/controllers/ShopController.java
app/plugins/Global.java
app/plugins/ProductionModule.java
app/tutorial/ClientFactory.java
build.sbt
it/controllers/ApplicationControllerIntegrationTest.java
it/testutils/WithPlayJavaClient.java
it/testutils/WithPlayJavaSphereClient.java
test/controllers/ApplicationControllerTest.java
test/controllers/CountryOperationsTest.java
test/controllers/WithSunriseApplication.java

Jepp, just quick fixes to make it work.

SDK migration 1.0.0-M10

---

app/controllers/CategoriesRefreshController.java
app/controllers/RefreshableCategoryTree.java
app/inject/CategoryTreeProvider.java
common/app/common/models/NavMenuData.java
conf/routes

Navigation menu (with refreshable tree) is back

---

app/inject/TemplateServiceProvider.java
common/app/common/templates/HandlebarsTemplateService.java
common/test/common/templates/HandlebarsTemplateTest.java
conf/application.conf

The same as we had in dmexco version

Enable handlebars cache, closes #147

---

app/inject/ProjectContextProvider.java
build.sbt
conf/application.conf

Get currencies from CTP project first

---

Procfile

Use correct artifactId.

---

app/tasks/TemplateFilesCopier.java
build.sbt

@schleichardt please review, specially the main method and naming stuff.

Provide task to copy template files into the project, closes #269

---

common/app/common/templates/HandlebarsTemplateService.java
product-catalog/app/productcatalog/common/GalleryData.java

Due to: https://github.com/jknack/handlebars.java/issues/150

Fix gallery by making array length available

---

build.sbt

Enable i18n YAML files copying to project

Allow to copy i18n YAML files to enable editing

---

ONBOARDING.md

@schleichardt @stmeissner can you take a look when you can (I will merge it meanwhile, as the whole documentation is WIP anyway).
Here is explained some basics and advanced customizations regarding templates.
It is still missing how to replace your template, how to customize i18n (but it requires some more work to make it really nice) and of course many more things.
Baby steps.

First documentation draft

---

common/test/common/i18n/YamlI18nResolverTest.java
common/test/resources/i18n/en/singlelong.yaml

I could not reproduce the bug, with exactly the same values that we had @mmoelli 
If it happens again, please let me know.

Implement test that tries to reproduce bug, unsuccessfully, closes #268

---

build.sbt
move-to-sdk/app/io/sphere/sdk/facets/BaseFacet.java
move-to-sdk/app/io/sphere/sdk/facets/Facet.java
move-to-sdk/app/io/sphere/sdk/facets/SelectFacetBuilder.java
move-to-sdk/app/io/sphere/sdk/facets/SelectFacetImpl.java
move-to-sdk/test/io/sphere/sdk/facets/SelectFacetBuilderTest.java
move-to-sdk/test/io/sphere/sdk/facets/SelectFacetTest.java
product-catalog/app/productcatalog/productoverview/SearchCriteria.java

@lauraluiz can you please merge if the build is green and if it is red, fix it?

Migrate to JVM SDK 1.0.0-RC1.

---

app.json
app/inject/ProductDataConfigProvider.java
build.sbt
common/app/common/models/ProductDataConfig.java
conf/application.conf
product-catalog/app/productcatalog/common/ProductBean.java
product-catalog/app/productcatalog/common/ProductVariantReferenceBean.java
product-catalog/app/productcatalog/common/SelectableProductAttributeBean.java
pt/inject/CtpModelsTestModule.java
public/javascripts/sunrise.js
public/stylesheets/sunrise.css

Enable hard/soft selectable attributes

Implement variant reload by selected attribute, closes #290

---

app/controllers/StatusController.java
common/app/common/actions/NoCache.java
common/app/common/actions/NoCacheAction.java
shopping-cart/app/shoppingcart/cartdetail/CartDetailPageController.java
shopping-cart/app/shoppingcart/checkout/address/CheckoutAddressPageContent.java
shopping-cart/app/shoppingcart/common/CartController.java

- health
- version
- cart
- checkout
Please @schleichardt take a look.

Do not cache some sensible endpoints, closes #296

---

app.json
conf/application.conf
conf/prod.conf

Also re-structure the configuration so it looks nicer (@schleichardt I think I managed to make it nice)

Include default configuration in Heroku, closes #297

---

README.md

* update the theme link
* remove the test link since it is outdated and unmaintained

update link to theme, remove automated tests link

---

build.sbt
project/build.properties

@lauraluiz please review/merge

move to JVM SDK 1.0.0-RC2

---

product-catalog/app/productcatalog/common/ProductBean.java
product-catalog/app/productcatalog/common/SelectableProductAttributeBean.java

Fix bug that prevented selectable attrs from working when an attribute didn't have a value

Fix selectable attrs bug when value doesn't exist, closes #356

---

app/reverserouter/ReverseRouterImpl.java
common/app/common/controllers/ReverseRouter.java
common/app/common/controllers/SunriseController.java
common/app/common/utils/FormUtils.java
common/app/myaccount/CustomerSessionUtils.java
common/app/shoppingcart/CartSessionUtils.java
common/app/shoppingcart/OrderSessionUtils.java
common/test/common/controllers/TestableReverseRouter.java
conf/i18n/en/my-account.yaml
conf/routes
conf/templates/my-account-personal-details.hbs
move-to-sdk/app/io/sphere/sdk/utils/FutureUtils.java
my-account/app/myaccount/login/LogInPageController.java
my-account/app/myaccount/mydetails/CustomerBean.java
my-account/app/myaccount/mydetails/MyPersonalDetailsFormBean.java
my-account/app/myaccount/mydetails/MyPersonalDetailsFormData.java
my-account/app/myaccount/mydetails/MyPersonalDetailsPageContent.java
my-account/app/myaccount/mydetails/MyPersonalDetailsPageController.java
my-account/app/myaccount/myorders/MyOrderPageContent.java
my-account/app/myaccount/myorders/MyOrdersPageContent.java
my-account/app/myaccount/myorders/MyOrdersPageController.java
my-account/app/myaccount/myorders/OrderOverviewBean.java
public/javascripts/sunrise.js
public/stylesheets/sunrise.css
shopping-cart/app/shoppingcart/checkout/address/AddressFormBean.java
shopping-cart/app/shoppingcart/checkout/confirmation/CheckoutConfirmationPageController.java

@schleichardt there's nothing really exciting to review, but maybe you catch something :)

My account details, close #186

---

README.md

fix Docker docu, close #385

---

conf/i18n/en/my-account.yaml
conf/routes
my-account/app/myaccount/addressbook/AddAddressFormData.java
my-account/app/myaccount/addressbook/AddressBookPageContent.java
my-account/app/myaccount/addressbook/AddressBookPageController.java
my-account/app/myaccount/addressbook/ChangeAddressFormData.java
my-account/app/myaccount/addressbook/RemoveAddressFormData.java

Simple structure following the same principles as with other controllers. No PageContent delivered.

Add first draft of address book

---

GUIDELINES.md
ONBOARDING.md
README.md
TESTING.md
app.json
setup-widget/app/setupwidget/views/setup.scala.html

@lauraluiz please review and merge

replace sphereio links with commercetools

---

app/reverserouter/ReverseRouterImpl.java
common/app/common/controllers/ReverseRouter.java
common/app/common/controllers/SunriseController.java
common/test/common/controllers/TestableReverseRouter.java
conf/routes
conf/templates/myaccount/my-account-sidebar.hbs
my-account/app/myaccount/myaddressbook/AddAddressFormData.java
my-account/app/myaccount/myaddressbook/ChangeAddressFormData.java
my-account/app/myaccount/myaddressbook/MyAddressBookPageContent.java
my-account/app/myaccount/myaddressbook/MyAddressBookPageController.java
my-account/app/myaccount/myaddressbook/RemoveAddressFormData.java

/cc @schleichardt (I don't think there is anything interesting though).

Use proper links in my account menu, closes #371

---

common/app/com/commercetools/sunrise/common/template/engine/TemplateEngineProvider.java
common/app/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsFactory.java
common/app/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsTemplateEngine.java
common/test/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsCmsHelperTest.java
common/test/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsI18NHelperTest.java
common/test/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsTemplateTest.java

handlebars creation override, close #429

---

common/app/com/commercetools/sunrise/common/basicauth/BasicAuthHttpFilters.java
common/app/com/commercetools/sunrise/play/SunriseApplicationLoader.java
common/app/com/commercetools/sunrise/play/SunriseConfiguration.java
common/app/com/commercetools/sunrise/play/SunriseHttpFilters.java
common/pt/com/commercetools/sunrise/common/basicauth/BasicAuthFilterTest.java
common/test/com/commercetools/sunrise/common/utils/SunriseConfigurationTest.java
conf/application.conf
my-account/app/com/commercetools/sunrise/myaccount/addressbook/addaddress/SunriseAddAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/addresslist/SunriseAddressBookController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/changeaddress/SunriseChangeAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/removeaddress/SunriseRemoveAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/login/SunriseLogInController.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/signup/SunriseSignUpController.java
my-account/app/com/commercetools/sunrise/myaccount/mydetails/SunriseMyPersonalDetailsController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/addtocart/SunriseAddProductToCartController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/cartdetail/SunriseCartDetailController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/changelineitemquantity/SunriseChangeLineItemQuantityController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/removelineitem/SunriseRemoveLineItemController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/address/SunriseCheckoutAddressController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/confirmation/SunriseCheckoutConfirmationController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/payment/SunriseCheckoutPaymentController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/shipping/SunriseCheckoutShippingController.java

Added global filter and removed annotations per action.

Added global filter for CSRF check

---

common/app/com/commercetools/sunrise/shoppingcart/CartBeanFactory.java
common/app/com/commercetools/sunrise/shoppingcart/CartLikeBeanFactory.java
common/app/com/commercetools/sunrise/shoppingcart/CartSessionUtils.java
common/app/com/commercetools/sunrise/shoppingcart/MiniCartBeanFactory.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/cartdetail/CartDetailPageContentFactory.java

Allow nullable cart in cart bean factories

---

common/app/com/commercetools/sunrise/common/controllers/WithForm.java
common/app/com/commercetools/sunrise/common/controllers/WithFormFlow.java
common/app/com/commercetools/sunrise/common/controllers/WithTemplateName.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/addaddress/SunriseAddAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/addresslist/SunriseAddressBookController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/changeaddress/SunriseChangeAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/addressbook/removeaddress/SunriseRemoveAddressController.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/login/SunriseLogInController.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/signup/SunriseSignUpController.java
my-account/app/com/commercetools/sunrise/myaccount/mydetails/SunriseMyPersonalDetailsController.java
my-account/app/com/commercetools/sunrise/myaccount/myorders/myorderdetail/SunriseMyOrderDetailController.java
my-account/app/com/commercetools/sunrise/myaccount/myorders/myorderlist/SunriseMyOrderListController.java
product-catalog/app/com/commercetools/sunrise/productcatalog/home/SunriseHomeController.java
product-catalog/app/com/commercetools/sunrise/productcatalog/productdetail/SunriseProductDetailController.java
product-catalog/app/com/commercetools/sunrise/productcatalog/productoverview/SunriseProductOverviewController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/addtocart/SunriseAddProductToCartController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/cartdetail/SunriseCartDetailController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/changelineitemquantity/SunriseChangeLineItemQuantityController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/removelineitem/SunriseRemoveLineItemController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/address/SunriseCheckoutAddressController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/confirmation/SunriseCheckoutConfirmationController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/payment/SunriseCheckoutPaymentController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/shipping/SunriseCheckoutShippingController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/thankyou/SunriseCheckoutThankYouController.java

/cc @schleichardt 
- WithTemplateName
- WithForm
- WithFormFlow

Rename framework interfaces

---

shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/cartdetail/SunriseCartDetailController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/changelineitemquantity/SunriseChangeLineItemQuantityController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/cart/removelineitem/SunriseRemoveLineItemController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/address/SunriseCheckoutAddressController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/confirmation/SunriseCheckoutConfirmationController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/payment/SunriseCheckoutPaymentController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/checkout/shipping/SunriseCheckoutShippingController.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/common/CartEmptyException.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/common/CartNotFoundException.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/common/PrimaryCartNotFoundException.java
shopping-cart/app/com/commercetools/sunrise/shoppingcart/common/SunriseFrameworkCartController.java

@schleichardt please review, I have simplified as well the names for the `require` methods.

Rename primary cart

---

common/app/com/commercetools/sunrise/common/models/ProductVariantBeanFactory.java
common/app/com/commercetools/sunrise/shoppingcart/CartLikeBeanFactory.java
common/app/com/commercetools/sunrise/shoppingcart/LineItemBeanFactory.java
my-account/app/com/commercetools/sunrise/myaccount/myorders/myorderlist/OrderOverviewBeanFactory.java

@schleichardt just a small PR with a tiny improvement before the big one (inject MoneyContext).

Extract moneycontext initialization to protected methods, closes #500

---

README.md

@stmeissner a quick documentation on how to start with Sunrise. I was inspired to do it right now so I went for it. Could you review it please?
/cc @schleichardt

Document how to use

---

project/plugins.sbt

@schleichardt last one. This time it requires for you to approve it :)

Update to Play Framework 2.5.9

---

build.sbt
common/app/com/commercetools/sunrise/shoppingcart/CartComponent.java
common/app/com/commercetools/sunrise/shoppingcart/CartFinderBySession.java
common/it/com/commercetools/sunrise/common/TestFixtures.java
common/it/com/commercetools/sunrise/common/WithSphereClient.java
common/it/com/commercetools/sunrise/shoppingcart/CartComponentIntegrationTest.java
common/test/com/commercetools/sunrise/common/sessions/TestableObjectStoringSessionStrategy.java

@schleichardt please could you review it?
Closes #546

Set customer email to cart, closes #546

---

build.sbt
sbt-tasks/app/com/commercetools/sunrise/theme/WebjarsFilesCopier.java

@schleichardt finally spotted this, please review

Remove theme dependency from released artifacts, sbt-tasks in particular

---

app/Module.java
common/app/com/commercetools/sunrise/common/ctp/MetricSphereClientProvider.java
conf/logback-reduced.xml
conf/logback.xml

So that it's easier to understand what it does

Rename metrics sphere client provider

---

common/app/com/commercetools/sunrise/common/models/ViewModel.java
common/app/com/commercetools/sunrise/common/template/engine/handlebars/HandlebarsContextFactory.java
common/app/com/commercetools/sunrise/common/template/engine/handlebars/SunriseJavaBeanValueResolver.java

Improve Hbs engine with extended view model and localized strings

---

common/app/com/commercetools/sunrise/common/utils/UrlUtils.java
common/test/com/commercetools/sunrise/common/utils/UrlUtilsTest.java

Url utils encode query params

---

.travis.yml

Remove automatic javadoc publishing

---

app/controllers/shoppingcart/CheckoutConfirmationController.java
app/controllers/shoppingcart/CheckoutPaymentController.java
app/controllers/shoppingcart/CheckoutShippingController.java
common/app/com/commercetools/sunrise/sessions/cart/CartPaymentInfoExpansionControllerComponent.java
common/app/com/commercetools/sunrise/sessions/cart/CartShippingInfoExpansionControllerComponent.java
shopping-cart/app/com/commercetools/sunrise/framework/CartFinderBySession.java

Add controller components to expand the cart for specific controllers.

---

common/app/com/commercetools/sunrise/framework/components/controllers/PageHeaderControllerComponentSupplier.java

Add missing controller component to page header component supplier.

---

common/app/com/commercetools/sunrise/sessions/CacheableObjectStoringSessionCookieStrategy.java
common/app/com/commercetools/sunrise/sessions/ObjectStoringSessionStrategy.java
common/app/com/commercetools/sunrise/sessions/SerializableObjectStoringSessionCookieStrategy.java
common/app/com/commercetools/sunrise/sessions/SessionCookieStrategy.java
common/app/com/commercetools/sunrise/sessions/SessionStrategy.java
common/app/com/commercetools/sunrise/sessions/customer/DefaultCustomerInSession.java
common/pt/com/commercetools/sunrise/sessions/CacheableObjectStoringSessionCookieStrategyTest.java
common/pt/com/commercetools/sunrise/sessions/SerializableObjectStoringSessionCookieStrategyTest.java
common/pt/com/commercetools/sunrise/sessions/SessionCookieStrategyTest.java

And fix potential bug with customer group.

Support nullable values on store method for session, closes #591

---

my-account/app/com/commercetools/sunrise/myaccount/authentication/changepassword/AbstractCustomerChangePasswordExecutor.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/changepassword/DefaultChangePasswordControllerAction.java
my-account/app/com/commercetools/sunrise/myaccount/authentication/changepassword/viemodels/ChangePasswordPageContentFactory.java

@katmatt it's what we already talked about on Monday.

Some improvements on change password

---

project/Release.scala

Update developers section

---

manual/Theme.md

Just realized it was a bit outdated :)

Update Theme Readme

---

common/app/com/commercetools/sunrise/framework/viewmodels/content/wishlist/WishlistItemViewModelFactory.java
project/Dependencies.scala

@lauraluiz fix for the heroku issue.

Fixing links issue

---

common/app/com/commercetools/sunrise/framework/viewmodels/content/products/ProductVariantReferenceViewModelMapFactory.java
common/app/com/commercetools/sunrise/framework/viewmodels/formatters/AttributeFormatter.java
common/app/com/commercetools/sunrise/framework/viewmodels/formatters/AttributeFormatterImpl.java

@katmatt I've fixed it, but didn't write tests for it. Pending for another day. But I made everything to handle nullable.

Fix attribute selector when there is an unused attribute for the product

---

common/app/com/commercetools/sunrise/ctp/SunriseSolutionInfo.java

Make SunriseSolutionInfo final and document how to provide your own

---

common/app/com/commercetools/sunrise/play/configuration/SunriseConfiguration.java
common/app/com/commercetools/sunrise/play/configuration/SunriseGuiceApplicationLoader.java
common/test/com/commercetools/sunrise/play/inject/SunriseConfigurationTest.java

Fix sunrise configuration, which now returns sunrise configuration too

---

common/app/com/commercetools/sunrise/search/facetedsearch/RangeUtils.java
common/app/com/commercetools/sunrise/search/facetedsearch/bucketranges/BucketRangeUtils.java
common/app/com/commercetools/sunrise/search/facetedsearch/bucketranges/viewmodels/BucketRangeFacetViewModelFactory.java

@katmatt this is the fix for the range facets. I've tested them manually carefully, but we still need the automated tests. As they are still not exposed, I would like to wait for the backend to fix the issues before really testing and documenting them, but at least I wanted to fix this bug. The related ticket is here: https://github.com/commercetools/commercetools-sunrise-java/issues/452

Fix range facets

---

common/app/com/commercetools/sunrise/common/contexts/RequestContext.java
common/app/com/commercetools/sunrise/common/contexts/RequestContextImpl.java
common/test/com/commercetools/sunrise/common/contexts/RequestContextTest.java

The code belongs to the v1.0.0-Mx version.

Fix encoding of URLs and make RequestContext an interface
